import 'package:raize/models/EventModel.dart';

class Autogenerated {
  String stauts;
  List<EventModel> eventList;

  Autogenerated({this.stauts, this.eventList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    stauts = json['stauts'];
    if (json['eventList'] != null) {
      eventList = new List<EventModel>();
      json['eventList'].forEach((v) {
        eventList.add(new EventModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['stauts'] = this.stauts;
    if (this.eventList != null) {
      data['eventList'] = this.eventList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}