FROM node:10-alpine

# Explicitly set the timezone to IST
RUN apk add --no-cache tzdata
ENV TZ=Asia/Kolkata

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 8080

CMD [ "npm", "start" ]